###
GET http://localhost:3000/api/tasks

###
GET https://api-rest-bunny.herokuapp.com/api/tasks

###
POST http://localhost:3001/api/tasks
Content-Type: application/json

{
    "description": "Create User task form",
    "user_id": "6016cb7fbbd7ac00151f2cb1"
}

###
GET http://localhost:3003/api/tasks/6016cb7fbbd7ac00151f2cb1

###
DELETE  http://localhost:3001/api/tasks/6014e56727c77d452c2f1476

###
PUT http://localhost:3001/api/tasks/6014e56727c77d452c2f1476
Content-Type: application/json

{
    "description": "EL cambio si aplica"
}


###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Raymond Lopez"
}

###
DELETE  http://localhost:3001/api/users/6015260b3513411f74d13723


###
POST https://api-rest-bunny.herokuapp.com/api/users
Content-Type: application/json

{
    "name": "James Sorensen"
}

###
PUT http://localhost:3001/api/users/6016315936a00500152d6078
Content-Type: application/json

{
    "name": "Joe Montana"
}